# Generated by Django 3.2.3 on 2021-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('isbn', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('cover', models.CharField(max_length=999)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
