# Generated by Django 3.2.3 on 2021-09-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_list', '0002_auto_20210914_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
