# Generated by Django 3.2.3 on 2021-09-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_list', '0003_rename_author_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
