# Generated by Django 3.2.3 on 2021-09-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_list', '0004_alter_book_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(blank=True, default=None, max_length=999, null=True),
        ),
    ]
