# Generated by Django 3.2.3 on 2021-09-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_list', '0006_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
